[platformio]
default_envs = m5core-basic-16m, m5core2, m5cores3

[env]
platform = espressif32@6.13.0
board_build.partitions = huge_app.csv
framework = arduino
lib_ldf_mode = deep+
monitor_speed = 115200
upload_speed = 1500000
lib_extra_dirs = ../../../..
lib_deps =
    m5stack/M5Unified@0.2.17
    m5stack/M5GFX@0.2.24
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DM5FACES_VALIDATION_FW=\"PIO2.9.0\"

[env:m5core-basic-16m]
board = m5stack-core-esp32-16M
build_flags =
    ${env.build_flags}
    -I .pio/libdeps/m5core-basic-16m/M5Unified/src

[env:m5core2]
board = m5stack-core2
build_flags =
    ${env.build_flags}
    -I .pio/libdeps/m5core2/M5Unified/src
    -DM5FACES_HOST_CORE2=1

[env:m5cores3]
board = m5stack-cores3
build_flags =
    ${env.build_flags}
    -I .pio/libdeps/m5cores3/M5Unified/src
    -DM5FACES_HOST_CORES3=1
